BarBlog/BarBlog.Web/Controllers/StaticPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BarBlog.BLL;
using BarBlog.Models;

namespace BarBlog.Web.Controllers
{
    public class StaticPageController : Controller
    {
        // GET: StaticPage
        public ActionResult PageIndex()
        {
            var manager = new AdminManager();
            var pages = manager.GetAllPages();
            return View(pages);
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult CreatePage()
        {
            return View(new StaticPage());
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult CreatePage(StaticPage page)
        {
            var manager = new AdminManager();
            var pageCount = manager.GetAllPages().Count;
            manager.AddPage(page);
            page.PageDate = DateTime.Now;
            if (pageCount == 0)
            {
                page.PageID = 1;
            }
            else
                page.PageID = manager.GetAllPages().Count + 1;
            return RedirectToAction("Index", "Home");
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult EditPage(int id)
        {
            var manager = new AdminManager();
            var page = manager.GetPageByID(id);

            return View(page);

        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult EditPage(StaticPage page)
        {
            //if (ModelState.IsValid)
            {
                var manager = new AdminManager();
                manager.EditPage(page);

            }
            return RedirectToAction("Index", "Home");
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ActionResult DeletePage(int id)
        {
            var manager = new AdminManager();
            var page = manager.GetPageByID(id);

            return View(page);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult DeletePage(StaticPage page)
        {
            //if (ModelState.IsValid)
            {
                var manager = new AdminManager();
                manager.DeletePage(page);
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult View(int id)
        {
            var manager = new AdminManager();
            var page = manager.GetPageByID(id);
            return View(page);
        }

    }
}

BarBlog/BarBlog.Web/Views/Shared/_BlogPostInputsPartial.cshtml
@using BarBlog.Models
@model BarBlog.Models.Post

<div id="PostForm">
    <div class="panel panel-primary">
        <div class="panel-heading">
            Post
        </div>
        <div class="panel-body">
            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true, "Validation Errors")
                <div class="form-group">
                    @Html.LabelFor(m => m.PostTitle)
                    @Html.TextBoxFor(m => m.PostTitle)
                    @Html.ValidationMessageFor(m => m.PostTitle)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.PostBody)
                    @Html.TextAreaFor(m => m.PostBody, new {id = "tinyMCE"})
                    @Html.ValidationMessageFor(m => m.PostBody)
                </div>
                
                <div class="form-group">
                    <label>Tags:</label>
                    @Html.TextBoxFor(m => m.placeholderText, new {id = "tagsList"})
                </div>
                <div class="form-group">
                    
                    @Html.Label("Post Category")

                    <select name="PostCategory.CategoryID" id="categoryID">
                       
                    </select>
                    <div class="form-group">
                        <label>Post Status:</label>
                        @if (User.IsInRole("Admin"))
                        {
                            @Html.EnumDropDownListFor(m => m.Status)
                        }
                    </div>
                    <button type="submit" class="btn btn-sm btn-secondary">Save</button>
                </div>
                

            }
            

        </div>
    </div>
</div>

@section Scripts
{
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/App/PostValidation.js"></script>
}

BarBlog/BarBlog.Web/Views/Shared/_BlogPostsPartial.cshtml
<!--Uses drawer.min.js-->
<!--drawer.js is written to be mobile first in the bootstrap style. Different column widths can be set in the same syntax as bootstrap columns-->
<div id="searchDrawer" class="drawer drawer-inside dw-xs-8 dw-sm-4 dw-lg-3 fold drawer-right" aria-labelledby="searchDrawer">
    <div class="drawer-contents">
        <div class="drawer-heading">
            <h2 class="drawer-title test">Filter Posts</h2>
        </div>
        <div class="drawer-body">

            <div class="input-group">
                <div><label for="query">Search: </label></div>
                <!--ng-model="<name>" is how the text box is binded to the angualr app so it can be referecned with $scope.<name>-->
                <div><input id="query" type="text" ng-model="query" /></div>
            </div>

            <div class="input-group">
                <div><label for="categoryName">Filter by category</label></div>
                <div>
                    <select name="PostCategory.CategoryID" id="categoryName" ng-model="PostCategory">
                        <option value="">None</option>
                    </select>
                </div>
            </div>

            @*<div class="input-group">
                <label for="tagName">Filter by tag</label>
                <form id="tagName"></form>
            </div>*@

            @*<label>Filter by dates</label>
                <!--Datepicker plugin. configured in the poorly named IndexFilterScripts.js-->
                <div class="input-daterange input-group" id="datepicker">
                    <input type="text" class="input-sm form-control" name="start" ng-model="startDate" />
                    <span class="input-group-addon">to</span>
                    <input type="text" class="input-sm form-control" name="end" ng-model="endDate" />
                </div>
                <!--End Datepicker-->*@

            <div class="input-group">
                <label for="pageSize">Items per page:</label>
                <input id="pageSize" type="number" min="1" max="100" class="form-control" ng-model="pageSize">
            </div>
        </div>
        <div class="drawer-footer">
            <div><small>Guild you will be missed!</small></div>
            <div><small>So long and thanks for all the fish!</small></div>
            <div><small><i class="fa fa-heart faa-pulse animated faa-fast" aria-hidden="true"></i> Alex</small></div>
        </div>
    </div>
</div>
<!--End searchDrawer-->
<div id="post_body">
    <div class="jumbotron" id="jumbotron-home">
        <h1>Regular Bar Reviews</h1>
    </div>
    @if (User.IsInRole("Admin"))
    {
        <div id="buttonBorder">
            <span>@Html.ActionLink("New Post", "CreatePost", "Admin", null, new { @class = "btn btn-sm btn-primary" })</span>
            <span>@Html.ActionLink("New Page", "CreatePage", "StaticPage", null, new { @class = "btn btn-sm btn-primary" })</span>
            <span>@Html.ActionLink("View Categories", "CategoryIndex", "Category", null, new { @class = "btn btn-sm btn-primary" })</span>
            <span>@Html.ActionLink("View Tags", "TagIndex", "Tag", null, new { @class = "btn btn-sm btn-primary" })</span>
        </div>
    }
    @if (User.IsInRole("Manager"))
    {
        <div id="buttonBorder">
            @Html.ActionLink("New Post", "CreatePost", "Subordinate", null, new { @class = "btn btn-sm btn-primary" })
        </div>
    }
    <div id="BlogPosts">
        <!--dir-paginate is used in place of ng-repeat-->
        <div class="BlogPost test" dir-paginate="post in BlogPosts | filter: {PostTags: {TagName: tag.key}} | filter: PostCategory | filter: search  | orderBy:'PostDate':true | itemsPerPage: pageSize" current-page="currentPage" pagination-id="lol">
            <h3>{{post.PostCategory.CategoryName}}: {{post.PostTitle}}</h3>
            <h6>{{post.PostDate | date:"MM/dd/yyyy"}}</h6>
            @if (User.Identity.IsAuthenticated)
            {
                <h6>Status: {{post.Status}}</h6>
            }
            
            <div ng-bind-html="post.PostBody"></div>
            <div id="tags">
                Tagged as:
                <span ng-repeat="tag in post.PostTags | orderBy:'TagName'">
                    <span>{{tag.TagName}}</span>
                </span>
            </div>
            @if (User.IsInRole("Admin"))
            {
                <div id="AdminButtons">
                    <a class="btn btn-sm btn-danger" href="/Admin/DeletePost/{{post.PostID}}">Delete</a>
                    <a class="btn btn-sm btn-danger" href="/Admin/EditPost/{{post.PostID}}">Edit</a>
                </div>
            } 
        </div>          
    </div>

    
    <!--Center is bad m'kay-->
    <!--To keep up with modern html standards elements on a page should be positioned with CSS-->
    <!--To save some time the center was used here since centering an element on a page can prove to be diffucult at times-->
    <center>
        <!--This is the pretty page switcher  that show up at the bottom of the page-->
        <!--Everything is handled by the plugin-->
        <!--The html is injected from the template-url blow-->
        <dir-pagination-controls boundary-links="true" pagination-id="lol" on-page-change="pageChangeHandler(newPageNumber)" template-url="/Scripts/App/dirPagination.tpl.html"></dir-pagination-controls>
    </center>
</div><!--End post_body-->

BarBlog/BarBlog.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Regular Bar Reviews</title>
    @RenderSection("styles", required: false)
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Scripts/FontAwesome/css/font-awesome.css" rel="stylesheet" />
    <!--Style Sheet is injected here-->
    <link class="theme" rel="stylesheet" type="text/css" href="~/Content/Site.css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Regular Bar Reviews", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @RenderSection("drawerControls", required: false)
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @*@if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Admin Mode", "Index", "Home")</li>
                    }
                    @if (User.IsInRole("Manager"))
                    {
                        <li>@Html.ActionLink("Manager Mode", "SubordinateIndex", "Subordinate")</li>
                    }*@

                    <!--staticPageDropdown-->
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">
                            Information Pages <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" id="staticPageDropdown">
                            <!--Populated by loadPages() in LayoutScritps-->
                        </ul>
                    </li>
                    <!--End staticPageDropdown-->
                    <!--Theme Switcher Dropdown-->
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">
                            Theme Picker <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" id="themeSwitcher">
                            <!--Themes to be switched between with ThemePicker() in LayoutScritps-->
                            <li><a href="#" rel="~/Content/Site.css">Alex's Generic Bar</a></li>
                            <li><a href="#" rel="~/Content/ThemeSwitcher/RavinWithDoug.css">Club Dougie Fresh</a></li>
                            <li><a href="#" rel="/Content/ThemeSwitcher/BlueLight.css">Jazzy Dan's</a></li>
                            <!--End Themes-->
                        </ul>
                    </li>
                    <!--End themeSwitcher Dropdown-->
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    <footer class="container">
        <p>&copy; @DateTime.Now.Year - Team Null</p>
    </footer>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/App/LayoutScripts.js"></script>
    @RenderSection("blogPostScripts", false)
    @RenderSection("scripts", required: false)
</body>
</html>

BarBlog/BarBlog.Web/Views/Shared/_StaticPageInputsPartial.cshtml
@model BarBlog.Models.StaticPage


<div id="pageform">
    <div class="panel panel-primary">
        <div class="panel-heading">
            Static Page
        </div>
        <div class="panel-body">
            @Html.ValidationSummary(true)
            <div class="form-group">
                @Html.LabelFor(m => m.PageTitle)
                @Html.TextBoxFor(m => m.PageTitle)
                @Html.ValidationMessageFor(m => m.PageTitle)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.PageBody)
                @Html.TextAreaFor(m => m.PageBody, new { id = "tinyMCE" })
                @Html.ValidationMessageFor(m => m.PageBody)
            </div>
        </div>
        <button type="submit" class="btn btn-sm btn-secondary" id="savepost">Save</button>
    </div>
</div>